version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: capstone_webapp
    volumes:
      - webapp_volume:/capstone
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=capstone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

volumes:
  webapp_volume: /mnt/d/Programming/Web\ Frameworks/Django/Docker/Capstone-A2/assignment
  db_volume: /mnt/d/Programming/Web\ Frameworks/Django/Docker/Capstone-A2/database