version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: capstone_webapp
    volumes:
      - .:/capstone
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=capstone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin